import { TokenType } from "../types.ts";

export const KEYWORDS: Record<string, TokenType> = {
  let: TokenType.Let,
  mut: TokenType.Mut,
  shadow: TokenType.Shadow,
  const: TokenType.Const,
  static: TokenType.Static,
  fn: TokenType.Fn,
  type: TokenType.Type,
  struct: TokenType.Struct,
  impl: TokenType.Impl,
  enum: TokenType.Enum,
  state_machine: TokenType.StateMachine,
  data: TokenType.Data,
  state: TokenType.State,
  any: TokenType.Any,
  yield: TokenType.Yield,
  gen: TokenType.Gen,
  async: TokenType.Async,
  await: TokenType.Await,
  if: TokenType.If,
  else: TokenType.Else,
  match: TokenType.Match,
  loop: TokenType.Loop,
  while: TokenType.While,
  for: TokenType.For,
  break: TokenType.Break,
  continue: TokenType.Continue,
  return: TokenType.Return,
  trait: TokenType.Trait,
  dyn: TokenType.Dyn,
  where: TokenType.Where,
  use: TokenType.Use,
  pub: TokenType.Pub,
  mod: TokenType.Mod,
};
