/**
 * Token types for Fax-lang lexer
 */

const TokenType = {
  // Keywords
  LET: 'LET',
  VAR: 'VAR',
  CONST: 'CONST',
  FN: 'FN',
  STRUCT: 'STRUCT',
  ENUM: 'ENUM',
  IF: 'IF',
  ELSE: 'ELSE',
  WHILE: 'WHILE',
  FOR: 'FOR',
  RETURN: 'RETURN',
  PUB: 'PUB',
  PRIV: 'PRIV',
  STATIC: 'STATIC',
  INT: 'INT',
  FLOAT: 'FLOAT',
  BOOL: 'BOOL',
  STRING: 'STRING',
  CHAR: 'CHAR',
  VOID: 'VOID',
  TRUE: 'TRUE',
  FALSE: 'FALSE',
  
  // Identifiers
  IDENTIFIER: 'IDENTIFIER',
  
  // Literals
  INTEGER_LITERAL: 'INTEGER_LITERAL',
  FLOAT_LITERAL: 'FLOAT_LITERAL',
  STRING_LITERAL: 'STRING_LITERAL',
  BOOLEAN_LITERAL: 'BOOLEAN_LITERAL',
  HEX_LITERAL: 'HEX_LITERAL',
  BINARY_LITERAL: 'BINARY_LITERAL',
  OCTAL_LITERAL: 'OCTAL_LITERAL',
  
  // Operators
  PLUS: 'PLUS',
  MINUS: 'MINUS',
  MULTIPLY: 'MULTIPLY',
  DIVIDE: 'DIVIDE',
  MODULO: 'MODULO',
  ASSIGN: 'ASSIGN',
  EQUAL: 'EQUAL',
  NOT_EQUAL: 'NOT_EQUAL',
  LESS_THAN: 'LESS_THAN',
  GREATER_THAN: 'GREATER_THAN',
  LESS_EQUAL: 'LESS_EQUAL',
  GREATER_EQUAL: 'GREATER_EQUAL',
  LOGICAL_AND: 'LOGICAL_AND',
  LOGICAL_OR: 'LOGICAL_OR',
  LOGICAL_NOT: 'LOGICAL_NOT',
  BITWISE_AND: 'BITWISE_AND',
  BITWISE_OR: 'BITWISE_OR',
  BITWISE_XOR: 'BITWISE_XOR',
  BITWISE_NOT: 'BITWISE_NOT',
  LEFT_SHIFT: 'LEFT_SHIFT',
  RIGHT_SHIFT: 'RIGHT_SHIFT',
  PLUS_ASSIGN: 'PLUS_ASSIGN',
  MINUS_ASSIGN: 'MINUS_ASSIGN',
  MULTIPLY_ASSIGN: 'MULTIPLY_ASSIGN',
  DIVIDE_ASSIGN: 'DIVIDE_ASSIGN',
  MODULO_ASSIGN: 'MODULO_ASSIGN',
  
  // Punctuation
  LEFT_PAREN: 'LEFT_PAREN',
  RIGHT_PAREN: 'RIGHT_PAREN',
  LEFT_BRACE: 'LEFT_BRACE',
  RIGHT_BRACE: 'RIGHT_BRACE',
  LEFT_BRACKET: 'LEFT_BRACKET',
  RIGHT_BRACKET: 'RIGHT_BRACKET',
  SEMICOLON: 'SEMICOLON',
  COMMA: 'COMMA',
  DOT: 'DOT',
  COLON: 'COLON',
  DOUBLE_COLON: 'DOUBLE_COLON',
  ARROW: 'ARROW',
  
  // Special
  EOF: 'EOF'
};

module.exports = { TokenType };