[book]
authors = ["Luvion1"]
language = "en"
src = "src"
title = "The Fax-lang Book"

[build]
build-dir = "../site/book"

[output.html]
git-repository-url = "https://github.com/Luvion1/Fax-lang"
edit-url-template = "https://github.com/Luvion1/Fax-lang/edit/main/book/{path}"

[preprocessor.links]
